services:
  steamapi:
    image: 'docker.io/awc89/sgnome-steam-api-proxy:latest'
    ports: [65300:3000]
    networks:
      - sgnome
    environment:
      STEAM_API_KEY: ${STEAM_API_KEY}
  steamgateway:
    image: 'docker.io/awc89/sgnome-steam-api-gateway:latest'
    ports: [65301:3000]
    networks:
      - sgnome
    environment:
      REDIS_HOST: ${REDIS_HOST}
      STEAM_API_URL: ${STEAM_API_URL}
  ownedgames:
    image: 'docker.io/awc89/sgnome-mfe-owned-games:latest'
    ports: [65302:3000, 3001:3001]
    networks:
      - sgnome
    environment:
      REDIS_HOST: ${REDIS_HOST}
      VITE_WS_PORT: 3001
      CORS_ORIGIN: 'http://localhost:65302'

networks:
  sgnome:
    driver: bridge